const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

async function sendSuspiciousTransactionEmail(transaction) {
  try {
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: process.env.ALERT_EMAIL,
      subject: "⚠️ Suspicious Transaction Detected",
      html: `
        <h2>Suspicious Transaction Alert</h2>

        <p><strong>Transaction ID:</strong> ${transaction.id}</p>
        <p><strong>From Wallet:</strong> ${transaction.fromWallet}</p>
        <p><strong>To Wallet:</strong> ${transaction.toWallet}</p>
        <p><strong>Amount:</strong> $${transaction.amount}</p>
        <p><strong>Risk Score:</strong> ${transaction.riskScore}</p>

        <hr />
        <p>Generated by eAUD AUSTRAC Monitoring System</p>
      `,
    });

    console.log("Suspicious transaction email sent");
  } catch (err) {
    console.error("Email failed:", err);
  }
}

module.exports = { sendSuspiciousTransactionEmail };